# Generated by Django 2.0 on 2018-08-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
