# Generated by Django 2.0 on 2018-08-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180802_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='airforce_number',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
