# Generated by Django 2.0 on 2018-08-02 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180802_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='airforce_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airforce_number', to=settings.AUTH_USER_MODEL),
        ),
    ]
