# Generated by Django 2.0 on 2018-08-02 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_remove_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='airforce_number',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
